# Generated by Django 5.0.3 on 2024-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_mainmenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemenu',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
