# Generated by Django 5.0.3 on 2024-03-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_treemenu_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='depth',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
