# Generated by Django 5.0.3 on 2024-03-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_treemenu_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treemenu',
            name='main_menu',
        ),
        migrations.DeleteModel(
            name='MainMenu',
        ),
    ]
