# Generated by Django 5.0.3 on 2024-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_treemenu_main_menu_delete_mainmenu'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='treemenu',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('name',), name='unique_name_per_parent_null'),
        ),
    ]
