# Generated by Django 5.0.3 on 2024-03-24 15:33

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_treemenu_unique_name_per_parent_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='name',
            field=models.CharField(max_length=100, validators=[menu.models.validate_no_slash]),
        ),
    ]
