# Generated by Django 5.0.3 on 2024-03-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_treemenu_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treemenu',
            name='unique_name_per_parent_null',
        ),
    ]
